services:
  postgres:
    image: postgres:17
    container_name: devroad-postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${BD_USER}
      POSTGRES_PASSWORD: ${BD_PASSWORD}
      POSTGRES_DB: ${BD_NAME}

    ports:
      - "${BD_PORT}:5432"

    volumes:
      - ./data/postgres:/var/lib/postgresql/data